name: Build ARM

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'examples/**'
      - 'lib/**'
      - 'hw/**'
      - 'tools/get_deps.py'
      - '.github/workflows/build_arm.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'examples/**'
      - 'lib/**'
      - 'hw/**'
      - 'tools/get_deps.py'
      - '.github/workflows/build_arm.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # ---------------------------------------
  # Build ARM family
  # ---------------------------------------
  build-arm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        family:
        # Alphabetical order
        #- 'broadcom_32bit'
        #- 'imxrt'
        #- 'lpc15'
        #- 'lpc18'
        #- 'lpc54'
        - 'lpc55'
        #- 'mm32'
        #- 'msp432e4'
        #- 'nrf'
        #- 'rp2040'
        #- 'samd11'
        #- 'samd21'
        #- 'samd51'
        #- 'saml2x'
        #- 'stm32f0'
        #- 'stm32f1'
        #- 'stm32f4'
        #- 'stm32f7'
        #- 'stm32g4'
        #- 'stm32h7'
        #- 'stm32l4'
        #- 'stm32wb'
        #- 'tm4c123'
        #- 'xmc4000'
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install ARM GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '11.2-2022.02'

    - name: Checkout TinyUSB
      uses: actions/checkout@v3

    - name: Checkout common submodules in lib
      run: git submodule update --init lib/FreeRTOS-Kernel lib/lwip lib/sct_neopixel-binho

    - name: Checkout hathach/linkermap
      uses: actions/checkout@v3
      with:
         repository: hathach/linkermap
         path: linkermap

    - name: Checkout pico-sdk for rp2040
      if: matrix.family == 'rp2040'
      run: |
        git clone --depth 1 -b develop https://github.com/raspberrypi/pico-sdk ~/pico-sdk
        echo >> $GITHUB_ENV PICO_SDK_PATH=~/pico-sdk

    - name: Get Dependencies
      run: python3 tools/get_deps.py ${{ matrix.family }}

    - name: Build
      run: python3 tools/build_make.py ${{ matrix.family }}
